//fitzroy
export const defaultLocation: [number, number] = [-37.801038, 144.979261];

// export const artists = [
//   "Astral Nadir",
//   "Dskreet",
//   "Sinch",
//   "PAM",
//   "Shida",
//   "Fikaris",
//   "Makatron",
//   "Tom Civil",
//   "FELLA",
//   "FB Jaba",
//   "Rone",
//   "Meggs",
//   "Adnate",
//   "Lushsux",
//   "Hense",
//   "Sofles",
//   "Fintan Magee",
//   "Roa",
//   "Pixel Pancho",
//   "Beastman",
//   "Hyuro",
//   "Everfresh",
//   "DabsMyla",
//   "Miso",
//   "TwoOne",
//   "Vexta",
//   "Phibs",
//   "Lucy Lucy",
//   "E.L.K",
//   "Holly Wilson",
//   "Kaffeine",
//   "Tessa Moran",
//   "Bailon",
//   "Jazmin Berakha",
// ];

export const suburbs = [
  "Fitzroy",
  "Collingwood",
  "Brunswick",
  "St Kilda",
  "Richmond",
  "Carlton",
  "South Yarra",
  "Prahran",
  "Footscray",
  "Northcote",
  "Cremorne",
];
